services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "praktikum"
    ports:
      - "5432:5432"
    volumes:
      - data_sql:/var/lib/postgresql/data   # Persistent data storage

volumes:
  data_sql: